"""
Django settings for wounded project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^_9z&@%@mtyx4*(a5%x1&7^fktmi=9pmq-m#wf6w89w3$9^qme'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'healtharchive.apps.HealtharchiveConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wounded.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wounded.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# stripe test keys
STRIPE_PUBLISHABLE_KEY = 'pk_test_51GrjUxHJZaUxPckxwDdaXBGNtz2HL8dyM77HKHfwxaLnW9ofJpxyBt8p7mDICujFndtGNmnqK8BHjlDrihCghlLa00SD5aVNEg'
STRIPE_SECRET_KEY = 'sk_test_51GrjUxHJZaUxPckxAjTbrt4TKyhcAY1oEI7IH2yARPw4HIMlTEMV5U8hgc5HIO0LfN7Iip8mus1ITFoNxzBYjgyd00rTEhe7cS'

# # stripe live keys
# STRIPE_PUBLISHABLE_KEY = 'pk_live_51GrjUxHJZaUxPckxxStjxsZk73Nl3E0r7qDBpjwrucHtyBkKfe8iEAAsEc7EUrxN8afSZSD175PmWUaycFZYolDi00k6c7w2rG' #os.environ.get('STRIPE_PUBLISHABLE_KEY')
# STRIPE_SECRET_KEY = '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' #os.environ.get('STRIPE_SECRET_KEY')