# Generated by Django 3.0.3 on 2020-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtharchive', '0003_auto_20201015_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humandiseasearchive',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='humandiseasearchive',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='humandiseasearchive',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
