# Generated by Django 3.0.3 on 2020-11-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtharchive', '0007_productlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
