# Generated by Django 3.0.3 on 2020-11-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtharchive', '0010_auto_20201119_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldiseasearchive',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='animal_disease_archive/'),
        ),
    ]
