# Generated by Django 3.0.3 on 2020-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtharchive', '0012_auto_20201119_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalinjuryarchive',
            name='img',
            field=models.ImageField(blank=True, upload_to='animal_injury_archive/'),
        ),
        migrations.AlterField(
            model_name='humandiseasearchive',
            name='img',
            field=models.ImageField(blank=True, upload_to='human_disease_archive/'),
        ),
        migrations.AlterField(
            model_name='humaninjuryarchive',
            name='img',
            field=models.ImageField(blank=True, upload_to='human_injury_archive/'),
        ),
        migrations.AlterField(
            model_name='humanpsychologyarchive',
            name='img',
            field=models.ImageField(blank=True, upload_to='human_psychology_archive/'),
        ),
    ]
