# Generated by Django 3.0.3 on 2020-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtharchive', '0013_auto_20201119_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSaleViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
